export const SESSION = 'SESSION'
export const USERDATA = 'USERDATA'
export const CURRENTPRICE = 'CURRENTPRICE'
export const NOTIFICATIONS = 'NOTIFICATIONS'
export const ORDER = 'ORDER'
export const CART = 'CART'
export const EARNING ='EARNING'